<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-E69K95O" name="Regression tests sprint 10.5" tests="5" failures="1" timestamp="27 Apr 2022 22:27:27 GMT" time="25.978" errors="0">
  <testcase name="checkOut" time="7.049" classname="sauceDemoTests.chekcoutEndtoEnd"/>
  <testcase name="validLogin" time="2.339" classname="sauceDemoTests.loginTest"/>
  <testcase name="invalidLogin" time="2.274" classname="sauceDemoTests.loginTest"/>
  <testcase name="validLogin" time="2.324" classname="sauceDemoTests.loginTestV2"/>
  <testcase name="invalidLogin" time="2.329" classname="sauceDemoTests.loginTestV2">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.comm/] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.comm/] but found [https://www.saucedemo.com/]
	at sauceDemoTests.loginTestV2.invalidLogin(loginTestV2.java:79)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
</testsuite> <!-- Regression tests sprint 10.5 -->
